spring.application.name=JobSonnar
server.port=${SERVER_PORT:8080}
jooble.api.key=${JOOBLE_API_KEY:}
adzuna.app.id=${ADZUNA_APP_ID:}
adzuna.app.key=${ADZUNA_APP_KEY:}
openwebninja.api.key=${OPENWEBNINJA_API_KEY:}
theirstack.api.key=${THIRESTACK_API_KEY:}
serper.api.key=${SERPER_API_KEY:}
search.cache.ttl-seconds=120
